### ISSUE TITLE
动态点云去除不干净问题？

### ISSUE THREAD

**Issue by maomao0220** [RongguangWu/OTD#2]
您好，在运行您的在线版本代码时，参数使用默认的参数，总是会出现动态物体去除不干净，很多保留在了地图上，其中动态物体主要是对面行驶的大车，而且也会把路边沿也是别成了动态点云，下面是运行效果：
![1](https://github.com/user-attachments/assets/b027926c-e650-4496-9983-8abe67cc859c)
![2](https://github.com/user-attachments/assets/b2f5db49-ad2c-4899-aa8f-c9851678b2fe)
![3](https://github.com/user-attachments/assets/8aec8b3e-7a63-4ac5-bfeb-3e5af2b2547c)

请问需要调节哪些参数已解决或减轻动态点云误识别以及漏识别？非常期待您的回复

**Comment by whw-create** [comment]
指望在线方法能过滤干净是很难的，只能尽量过滤一下

**Comment by RongguangWu** [comment]
可能有部分困难的场景确实会过滤不干净，但是这个场景应该还是可以去干净的的。可能需要注意几个问题，第一检查一下地面分割的情况，是否分割正确。第二是确定一下动态的车辆是否是在原地停了很久才动的，如果是的话那可能会处理不掉。第三可以尝试将tau_ratio增大看一下效果，该参数越大去除效果越好，但同样的误杀现象也会更加严重。
另外关于路边点误杀的情况，根本原因还是地面分割的问题，那块区域出现偶尔被识别为地面点，偶尔被识别为非地面点的情况。可以看一下地图剩余的部分是否是完整的，如果完整的话那这部分误杀就是可以不用考虑的。

**Comment by whw-create** [comment]
> 可能有部分困难的场景确实会过滤不干净，但是这个场景应该还是可以去干净的的。可能需要注意几个问题，第一检查一下地面分割的情况，是否分割正确。第二是确定一下动态的车辆是否是在原地停了很久才动的，如果是的话那可能会处理不掉。第三可以尝试将tau_ratio增大看一下效果，该参数越大去除效果越好，但同样的误杀现象也会更加严重。 另外关于路边点误杀的情况，根本原因还是地面分割的问题，那块区域出现偶尔被识别为地面点，偶尔被识别为非地面点的情况。可以看一下地图剩余的部分是否是完整的，如果完整的话那这部分误杀就是可以不用考虑的。

哥们你这个方法需要当前帧的位姿初值准确吗

**Comment by whw-create** [comment]
> > 可能有部分困难的场景确实会过滤不干净，但是这个场景应该还是可以去干净的的。可能需要注意几个问题，第一检查一下地面分割的情况，是否分割正确。第二是确定一下动态的车辆是否是在原地停了很久才动的，如果是的话那可能会处理不掉。第三可以尝试将tau_ratio增大看一下效果，该参数越大去除效果越好，但同样的误杀现象也会更加严重。 另外关于路边点误杀的情况，根本原因还是地面分割的问题，那块区域出现偶尔被识别为地面点，偶尔被识别为非地面点的情况。可以看一下地图剩余的部分是否是完整的，如果完整的话那这部分误杀就是可以不用考虑的。
> 
> 哥们你这个方法需要当前帧的位姿初值准确吗

没仔细看代码和论文，我以为是跑里程计前过滤一下动态点云那种在线呢

**Comment by RongguangWu** [comment]
得位姿比较准才行，要不然会有挺多的误去除现象

**Comment by maomao0220** [comment]
请问，输出的非地面点云是包含动态点云的吧？有什么好的办法输出静态点云地图吗（地面点加上去除动态点云之后的非地面点）？ @RongguangWu @whw-create

**Comment by RongguangWu** [comment]
我印象里应该会发布地面地图、非地面静态地图和非地面动态地图的，但是是否会保存点云我忘记了。如果没有的话可以根据消息发布的点云自己加一段保存的代码

**Comment by maomao0220** [comment]
好的，试了增大tau_ratio后，动态点云还是去除效果不好 @RongguangWu

**Comment by RongguangWu** [comment]
![地面分割](https://github.com/user-attachments/assets/8d54101c-54e6-40f4-be96-f5fd6a7f64da)
您这里的这个场景即使是tau_ratio为0.7甚至是0.5也不应该出问题，因为论文中测试的场景要比这困难的多，所以我猜测可能还是地面分割的问题。可以在rviz中显示一下这两项，这显示的是单帧的地面分割结果，看一下是不是在一些情况下动态车辆周围（不包括车辆下面，车辆正下方被遮挡，就应该检测不到地面）的地面是否能分割出来。

**Comment by maomao0220** [comment]
好的，这里我这个场景是矿山场景，运行的车辆都是较大的矿车，雷达安装在车头中心部位。动态点去不干净和这种大车辆场景有关吗？

**Comment by maomao0220** [comment]
您好，对于动态车辆下面点云可以去除的很干净，但是对于上面部分的点云扔存在拖影现象而没有去除（绿色框所示），会车时有一个车身的点云去不干净（蓝色框所示），请问该怎么调整算法或参数？这和动态车辆太高的缘故吗？
![微信图片_20240928112944](https://github.com/user-attachments/assets/b51373e8-cbbe-48a6-8faa-83d86434021f)

**Comment by maomao0220** [comment]
https://github.com/user-attachments/assets/80bdfdb7-75cc-4e7d-b6f6-0a349f2dd74b

**Comment by RongguangWu** [comment]
确实应该是高度的问题，我在代码里面设置了只去除3m以内的点，你可以修改一下

**Comment by RongguangWu** [comment]
在otd.h文件的364行那里
![image](https://github.com/user-attachments/assets/6a64deea-940b-4ec7-93b2-b2d17b937817)

**Comment by wt2excellent** [comment]
> 在otd.h文件的364行那里 ![image](https://private-user-images.githubusercontent.com/133629721/371747771-6a64deea-940b-4ec7-93b2-b2d17b937817.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg1MjkzNjMsIm5iZiI6MTcyODUyOTA2MywicGF0aCI6Ii8xMzM2Mjk3MjEvMzcxNzQ3NzcxLTZhNjRkZWVhLTk0MGItNGVjNy05M2IyLWIyZDE3YjkzNzgxNy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDEwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAxMFQwMjU3NDNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05N2NlYjI1OTFkYTc0ZmM3NDNhZTg4NTlmODMyOWU4OTUwMDY2NjkwNGQ1OTdlMDBjMWM0YTQ1NzRhMGFkMDg0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.xYcSGRHtju4DXn4UlijVM7_O0k2mYM8blTgtm0GcBss)

![image](https://github.com/user-attachments/assets/556ee550-82eb-4a0a-bb01-8011ef943e6c)
您好呀，我运行sementicKITTI数据集序列01，并不能完全复现文章中的数据，这个有哪些参数需要调整吗？

**Comment by wt2excellent** [comment]
> > 在otd.h文件的364行那里 ![image](https://private-user-images.githubusercontent.com/133629721/371747771-6a64deea-940b-4ec7-93b2-b2d17b937817.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg1MjkzNjMsIm5iZiI6MTcyODUyOTA2MywicGF0aCI6Ii8xMzM2Mjk3MjEvMzcxNzQ3NzcxLTZhNjRkZWVhLTk0MGItNGVjNy05M2IyLWIyZDE3YjkzNzgxNy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDEwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAxMFQwMjU3NDNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05N2NlYjI1OTFkYTc0ZmM3NDNhZTg4NTlmODMyOWU4OTUwMDY2NjkwNGQ1OTdlMDBjMWM0YTQ1NzRhMGFkMDg0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.xYcSGRHtju4DXn4UlijVM7_O0k2mYM8blTgtm0GcBss)
> 
> ![image](https://private-user-images.githubusercontent.com/92638700/375200119-556ee550-82eb-4a0a-bb01-8011ef943e6c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg1MzEyMjcsIm5iZiI6MTcyODUzMDkyNywicGF0aCI6Ii85MjYzODcwMC8zNzUyMDAxMTktNTU2ZWU1NTAtODJlYi00YTBhLWJiMDEtODAxMWVmOTQzZTZjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDEwVDAzMjg0N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTdmYzZiMjg3OGQwMzI5NWE5NWNhZjhiNGIxYWI0ZjdlNDZmZWM2NWZmNDc4OTNmOTI0MDhkZTYzZGRiODMyOTMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.lE-CKqAxkdnKyUxK4dv31LAJxQMauNQISuSbEg4qN3c) 您好呀，我运行sementicKITTI数据集序列01，并不能完全复现文章中的数据，这个有哪些参数需要调整吗？

@RongguangWu @maomao0220

**Comment by wt2excellent** [comment]
> > > 在otd.h文件的364行那里 ![image](https://private-user-images.githubusercontent.com/133629721/371747771-6a64deea-940b-4ec7-93b2-b2d17b937817.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg1MjkzNjMsIm5iZiI6MTcyODUyOTA2MywicGF0aCI6Ii8xMzM2Mjk3MjEvMzcxNzQ3NzcxLTZhNjRkZWVhLTk0MGItNGVjNy05M2IyLWIyZDE3YjkzNzgxNy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDEwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAxMFQwMjU3NDNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05N2NlYjI1OTFkYTc0ZmM3NDNhZTg4NTlmODMyOWU4OTUwMDY2NjkwNGQ1OTdlMDBjMWM0YTQ1NzRhMGFkMDg0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.xYcSGRHtju4DXn4UlijVM7_O0k2mYM8blTgtm0GcBss)
> > 
> > 
> > ![image](https://private-user-images.githubusercontent.com/92638700/375200119-556ee550-82eb-4a0a-bb01-8011ef943e6c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg1MzEyMjcsIm5iZiI6MTcyODUzMDkyNywicGF0aCI6Ii85MjYzODcwMC8zNzUyMDAxMTktNTU2ZWU1NTAtODJlYi00YTBhLWJiMDEtODAxMWVmOTQzZTZjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDEwVDAzMjg0N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTdmYzZiMjg3OGQwMzI5NWE5NWNhZjhiNGIxYWI0ZjdlNDZmZWM2NWZmNDc4OTNmOTI0MDhkZTYzZGRiODMyOTMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.lE-CKqAxkdnKyUxK4dv31LAJxQMauNQISuSbEg4qN3c) 您好呀，我运行sementicKITTI数据集序列01，并不能完全复现文章中的数据，这个有哪些参数需要调整吗？
> 
> @RongguangWu @maomao0220

这个运行KITTI测试数据集02片段，点云地图显示不出来呢？

**Comment by wt2excellent** [comment]
> > > 在otd.h文件的364行那里 ![image](https://private-user-images.githubusercontent.com/133629721/371747771-6a64deea-940b-4ec7-93b2-b2d17b937817.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg1MjkzNjMsIm5iZiI6MTcyODUyOTA2MywicGF0aCI6Ii8xMzM2Mjk3MjEvMzcxNzQ3NzcxLTZhNjRkZWVhLTk0MGItNGVjNy05M2IyLWIyZDE3YjkzNzgxNy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDEwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAxMFQwMjU3NDNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05N2NlYjI1OTFkYTc0ZmM3NDNhZTg4NTlmODMyOWU4OTUwMDY2NjkwNGQ1OTdlMDBjMWM0YTQ1NzRhMGFkMDg0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.xYcSGRHtju4DXn4UlijVM7_O0k2mYM8blTgtm0GcBss)
> > 
> > 
> > ![image](https://private-user-images.githubusercontent.com/92638700/375200119-556ee550-82eb-4a0a-bb01-8011ef943e6c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg1MzEyMjcsIm5iZiI6MTcyODUzMDkyNywicGF0aCI6Ii85MjYzODcwMC8zNzUyMDAxMTktNTU2ZWU1NTAtODJlYi00YTBhLWJiMDEtODAxMWVmOTQzZTZjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDEwVDAzMjg0N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTdmYzZiMjg3OGQwMzI5NWE5NWNhZjhiNGIxYWI0ZjdlNDZmZWM2NWZmNDc4OTNmOTI0MDhkZTYzZGRiODMyOTMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.lE-CKqAxkdnKyUxK4dv31LAJxQMauNQISuSbEg4qN3c) 您好呀，我运行sementicKITTI数据集序列01，并不能完全复现文章中的数据，这个有哪些参数需要调整吗？
> 
> @RongguangWu @maomao0220

![image](https://github.com/user-attachments/assets/c352459c-1e47-42f0-a619-af44b97a6c75)
这个运行测试数据集02片段，rviz没有显示呢？非常期待您的回复。

**Comment by RongguangWu** [comment]
> > > > 在otd.h文件的364行那里 ![image](https://private-user-images.githubusercontent.com/133629721/371747771-6a64deea-940b-4ec7-93b2-b2d17b937817.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg1MjkzNjMsIm5iZiI6MTcyODUyOTA2MywicGF0aCI6Ii8xMzM2Mjk3MjEvMzcxNzQ3NzcxLTZhNjRkZWVhLTk0MGItNGVjNy05M2IyLWIyZDE3YjkzNzgxNy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDEwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAxMFQwMjU3NDNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05N2NlYjI1OTFkYTc0ZmM3NDNhZTg4NTlmODMyOWU4OTUwMDY2NjkwNGQ1OTdlMDBjMWM0YTQ1NzRhMGFkMDg0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.xYcSGRHtju4DXn4UlijVM7_O0k2mYM8blTgtm0GcBss)
> > > 
> > > 
> > > ![image](https://private-user-images.githubusercontent.com/92638700/375200119-556ee550-82eb-4a0a-bb01-8011ef943e6c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg1MzEyMjcsIm5iZiI6MTcyODUzMDkyNywicGF0aCI6Ii85MjYzODcwMC8zNzUyMDAxMTktNTU2ZWU1NTAtODJlYi00YTBhLWJiMDEtODAxMWVmOTQzZTZjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDEwVDAzMjg0N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTdmYzZiMjg3OGQwMzI5NWE5NWNhZjhiNGIxYWI0ZjdlNDZmZWM2NWZmNDc4OTNmOTI0MDhkZTYzZGRiODMyOTMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.lE-CKqAxkdnKyUxK4dv31LAJxQMauNQISuSbEg4qN3c) 您好呀，我运行sementicKITTI数据集序列01，并不能完全复现文章中的数据，这个有哪些参数需要调整吗？
> > 
> > 
> > @RongguangWu @maomao0220
> 
> ![image](https://private-user-images.githubusercontent.com/92638700/375215391-c352459c-1e47-42f0-a619-af44b97a6c75.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzE5MzkxOTAsIm5iZiI6MTczMTkzODg5MCwicGF0aCI6Ii85MjYzODcwMC8zNzUyMTUzOTEtYzM1MjQ1OWMtMWU0Ny00MmYwLWE2MTktYWY0NGI5N2E2Yzc1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTE4VDE0MDgxMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTc1M2VlNWViMzhmMzQxNjY3YWIxNzFmMmFkOTFkZGM4NmZiNDk4YjNjMzI1MGNjY2IyNzk0ZWZjZDUyMmYxMTUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.wReDWvNHyPu0NcWjDVRdvXRl1Rb6lt7R6-mKhdc3efo) 这个运行测试数据集02片段，rviz没有显示呢？非常期待您的回复。

我记得里面有kitti01的yaml，直接用那个运行局就可以了。这套代码经过我的整理后在5个数据集上运行完的指标应该都是比论文中写的是要高的。kitti02你可能得拖动一下rviz找一下，地图可能并不在原点周围

**Comment by RongguangWu** [comment]
> > 在otd.h文件的364行那里 ![image](https://private-user-images.githubusercontent.com/133629721/371747771-6a64deea-940b-4ec7-93b2-b2d17b937817.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg1MjkzNjMsIm5iZiI6MTcyODUyOTA2MywicGF0aCI6Ii8xMzM2Mjk3MjEvMzcxNzQ3NzcxLTZhNjRkZWVhLTk0MGItNGVjNy05M2IyLWIyZDE3YjkzNzgxNy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDEwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAxMFQwMjU3NDNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05N2NlYjI1OTFkYTc0ZmM3NDNhZTg4NTlmODMyOWU4OTUwMDY2NjkwNGQ1OTdlMDBjMWM0YTQ1NzRhMGFkMDg0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.xYcSGRHtju4DXn4UlijVM7_O0k2mYM8blTgtm0GcBss)
> 
> ![image](https://private-user-images.githubusercontent.com/92638700/375200119-556ee550-82eb-4a0a-bb01-8011ef943e6c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzE5NDA0MjMsIm5iZiI6MTczMTk0MDEyMywicGF0aCI6Ii85MjYzODcwMC8zNzUyMDAxMTktNTU2ZWU1NTAtODJlYi00YTBhLWJiMDEtODAxMWVmOTQzZTZjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTE4VDE0Mjg0M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTRkNzlkNWM0ZWIzOGEwZDFmY2FmMjE0NTE5ODRlMzgwNmRiNTE1MDc4NGE4M2QxOGRiZjQ0OGVkY2Q0ZTNlNzgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.JSbWpWMnGV0FTEyNpHHO8763t5AFMbGMAemagkbylvc) 您好呀，我运行sementicKITTI数据集序列01，并不能完全复现文章中的数据，这个有哪些参数需要调整吗？

我刚刚试了一下，确实有点儿问题,现已更新

**Comment by wt2excellent** [comment]
> > > 在otd.h文件的364行那里 ![image](https://private-user-images.githubusercontent.com/133629721/371747771-6a64deea-940b-4ec7-93b2-b2d17b937817.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg1MjkzNjMsIm5iZiI6MTcyODUyOTA2MywicGF0aCI6Ii8xMzM2Mjk3MjEvMzcxNzQ3NzcxLTZhNjRkZWVhLTk0MGItNGVjNy05M2IyLWIyZDE3YjkzNzgxNy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDEwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAxMFQwMjU3NDNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05N2NlYjI1OTFkYTc0ZmM3NDNhZTg4NTlmODMyOWU4OTUwMDY2NjkwNGQ1OTdlMDBjMWM0YTQ1NzRhMGFkMDg0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.xYcSGRHtju4DXn4UlijVM7_O0k2mYM8blTgtm0GcBss)
> > 
> > 
> > ![image](https://private-user-images.githubusercontent.com/92638700/375200119-556ee550-82eb-4a0a-bb01-8011ef943e6c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzE5NDA0MjMsIm5iZiI6MTczMTk0MDEyMywicGF0aCI6Ii85MjYzODcwMC8zNzUyMDAxMTktNTU2ZWU1NTAtODJlYi00YTBhLWJiMDEtODAxMWVmOTQzZTZjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTE4VDE0Mjg0M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTRkNzlkNWM0ZWIzOGEwZDFmY2FmMjE0NTE5ODRlMzgwNmRiNTE1MDc4NGE4M2QxOGRiZjQ0OGVkY2Q0ZTNlNzgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.JSbWpWMnGV0FTEyNpHHO8763t5AFMbGMAemagkbylvc) 您好呀，我运行sementicKITTI数据集序列01，并不能完全复现文章中的数据，这个有哪些参数需要调整吗？
> 
> 我刚刚试了一下，确实有点儿问题,现已更新
非常感谢您的工作
